name: merge-models

services:
  web:
    image: nginx:1.27-alpine
    container_name: merge-models
    ports:
      - "18447:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
