server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json application/wasm image/svg+xml;

    add_header Permissions-Policy "accelerometer=(self), gyroscope=(self)" always;
    add_header Feature-Policy "accelerometer 'self'; gyroscope 'self'" always;

    location = /index.html {
        add_header Cache-Control "no-cache";
        add_header Permissions-Policy "accelerometer=(self), gyroscope=(self)" always;
        add_header Feature-Policy "accelerometer 'self'; gyroscope 'self'" always;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Permissions-Policy "accelerometer=(self), gyroscope=(self)" always;
        add_header Feature-Policy "accelerometer 'self'; gyroscope 'self'" always;
    }
}
